name: Build and deploy CFN resource provider
on: [push]
  # push:
    # tags:
    # - "*"
    # branches: main
permissions:
  id-token: write
  contents: read
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: 'maven'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
        cache: 'pip'
    - run: pip install cloudformation-cli-java-plugin boto3
    - run: echo "Building with Java version - $(java -version)"
    - run: mvn package
    - run: cfn submit --dry-run
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-central-1
    - name: upload assets to s3
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: python deployment/upload_s3.py
